stages:
  - copie
  - deploy
  - test_integration
variables:
  ARCHIVE_NAME: ${CI_PROJECT_PATH_SLUG}

test_integration:
  stage: test_integration
  only:
    - preprod
    - dev
  script:
    - newman run ./postman_collection/igo2-apercu-qc.postman_collection.json --environment ./postman_collection/${CI_COMMIT_REF_NAME}.postman_environment.json

copie:
  stage: copie
  script:
    - rm -f ./${ARCHIVE_NAME}.tar.gz
    - touch ./${ARCHIVE_NAME}.tar.gz
    - tar --exclude='./.git' --exclude='./.gitlab-ci.yml' --exclude='./postman_collection' --exclude=./${ARCHIVE_NAME}.tar.gz -czvf ./${ARCHIVE_NAME}.tar.gz ./
    - scp -v ./${ARCHIVE_NAME}.tar.gz synchrogitlab@spssogl97d:/srv/majdata/synchrogitlab/ARCHIVES/
  only:
    - dev
    - preprod
    - tags
  artifacts:
    paths:
        - ${ARCHIVE_NAME}.tar.gz
    name: ${CI_COMMIT_REF_NAME}-${CI_PROJECT_PATH_SLUG}
    when: on_success
    expire_in: 1 week
    
synchro_dev:
  stage: deploy
  when: manual
  script:
    - "ssh synchrogitlab@spssogl97d \"sh ~/bin/synchro_envgitlab.sh ${ARCHIVE_NAME} /srv/www/geomatique/apps/${CI_PROJECT_PATH} ${CI_COMMIT_REF_NAME} config\""
  only:
    - dev
  environment: ${CI_COMMIT_REF_NAME}
  artifacts:
    paths:
        - ${ARCHIVE_NAME}.tar.gz
    name: ${CI_COMMIT_REF_NAME}-${CI_PROJECT_PATH_SLUG}
    when: on_success
    expire_in: 1 week
  dependencies:
    - copie

synchro_preprod:
  stage: deploy
  script:
    - "ssh synchrogitlab@spssogl97d \"sh ~/bin/synchro_envgitlab.sh ${ARCHIVE_NAME} /srv/www/geomatique/apps/${CI_PROJECT_PATH} dev config\""
    - "ssh synchrogitlab@spssogl97d \"sh ~/bin/synchro_envgitlab.sh ${ARCHIVE_NAME} /srv/www/geomatique/apps/${CI_PROJECT_PATH} preprod config\""
  only:
    - preprod
  environment: ${CI_COMMIT_REF_NAME}
  artifacts:
    paths:
        - ${ARCHIVE_NAME}.tar.gz
    name: ${CI_COMMIT_REF_NAME}-${CI_PROJECT_PATH_SLUG}
    when: on_success
    expire_in: 1 week
  dependencies:
    - copie
    
synchro_prod:
  stage: deploy
  script:
    - "ssh synchrogitlab@spssogl97d \"sh ~/bin/synchro_envgitlab.sh ${ARCHIVE_NAME} /srv/www/geomatique/apps/${CI_PROJECT_PATH} prod config\""
  only:
    - tags
  environment: prod
  artifacts:
    paths:
        - ${ARCHIVE_NAME}.tar.gz
    name: ${CI_COMMIT_REF_NAME}-${CI_PROJECT_PATH_SLUG}
    when: on_success
    expire_in: 1 week
  dependencies:
    - copie

